### PR TITLE
Cleanup dependencies

### PR DESCRIPTION
**Pull request by isovector**
Just a quick PR to get this down to the core library. Seems to build on my machine.

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks for the PR! While this is the general direction I'd like to take, my preference is to keep most examples and document them. So it will take a bit more work.

**Comment by isovector** [comment]
How would you feel about moving them into an `examples` folder for the time being?

**Comment by snowleopard** [comment]
@isovector That's exactly the approach I'm taking (haven't pushed it yet since it's a mess at the moment). 

How urgent is it for you to have this package on Hackage? I think I can finalise this work and release the library by end of today if need be.

**Comment by isovector** [comment]
Urgent, no, but I'm excited to refactor [ecstasy](https://hackage.haskell.org/package/ecstasy) into selective functors---I'm expecting roughly a 10x perf gain from the static analysis. 

That being said, I have lots of other projects to keep me busy! I just thought I'd shoot this PR your way in case the issue was "I just finished writing a damn big paper and the thought of doing more work on this in the near future is untenable" :)

**Comment by snowleopard** [comment]
> Urgent, no, but I'm excited to refactor ecstasy into selective functors---I'm expecting roughly a 10x perf gain from the static analysis.

Wow! This sounds so exciting that I'd like release the library for you as soon as possible :-)

> I just thought I'd shoot this PR your way in case the issue was "I just finished writing a damn big paper and the thought of doing more work on this in the near future is untenable" :)

To be honest, that's not too far from how I feel, but I do want to release the library sooner rather than later, so I've been working on the release already. I'll ping you in a few hours with how it goes.

**Comment by snowleopard** [comment]
Done: http://hackage.haskell.org/package/selective

@isovector This fully subsumes this PR, so closing. Thank you for the encouragement :)

**Pull request closed without merging**
