### PR TITLE
Add biselect implementation from the paper

### PR DESCRIPTION
**Pull request by dredozubov**
This change is [Reviewable](https://reviewable.io/reviews/snowleopard/selective/19)

### CODE REVIEW

**Comment by dredozubov** [comment]
Apparently it's in `test/Sketch.hs`, but it's not clear to me why it's defined there and not in the main source tree.

**Comment by snowleopard** [comment]
It's not yet in the main module for two reasons:
* Adding it simply as a function doesn't seem to be useful, because by implementing it via `select` we break the symmetry and cannot really be speculative in both arguments. We really need to add `biselect` to the type class itself! 
* I think I'll add it to the type class, but after finishing off the ICFP paper and the associated artefact, because I'd like it to match the paper. As soon as the paper and the artefact are out, I'll start further changes/improvements.

We can keep this PR open, I'll address it at some point.

**Comment by snowleopard** [comment]
P.S.: Thanks for the PR and for the chat after the talk! :)

**Comment by dredozubov** [comment]
I guess I’ll just close it then, thanks.

**Pull request closed without merging**
