### PR TITLE
Allow GHC 9.4

### LINKED ISSUE #59: Unexpected test success Tests.Validation.Theorems.Interchange
Hello, I get an unexpected test success when trying to compile selective 0.5 using ghc 9.4.

OK (expected failure): Tests.Validation.Theorems.(f <*> g) == (f `apS` g)

Unexpected test success:
    Tests.Validation.Theorems.Interchange: (x *> (y <*? z)) == ((x *> y) <*? z)

Has anyone got any idea there?

Thanks

### PR DESCRIPTION
**Pull request by turion**
PR to test, debug and hopefully resolve #59

### CODE REVIEW

**Comment by turion** [comment]
It seems that https://github.com/snowleopard/neil needs to be updated first before we can continue here. And for some reason the installer for GHC 9.4 fails.

**Comment by snowleopard** [comment]
Sorry, I'm confused about how this relates to #59. Could you clarify?

**Comment by turion** [comment]
Ah, I was under the wrong assumption that the error message is caused by moving to GHC 9.4! But apparently it isn't, sorry.

**Comment by snowleopard** [comment]
Closing in favour of #66.

**Pull request closed without merging**
