### PR TITLE
Add less restrictive Selective (WriterT w) instances

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by snowleopard** [comment]
The implementation looks cool but I don't think that it's actually correct. If the first argument holds `Left a, w`, aren't you going to drop `w` on the floor?

One hint that something is wrong is that you're not really using the monoid instance.

**Comment by snowleopard** [comment]
It looks fixable though: you'll need to turn `f (Either a b, w)` to `f (Either (a, w) (b, w))` and `f (a -> b, w)` to `f ((a, w) -> (b, w))`.

**Comment by turion** [comment]
So the mistake here is not that it's an unlawful `Selective`, but that it doesn't coincide with `selectM`, it seems. I'll add some regression tests as well.

**Comment by turion** [comment]
Ah no, the identity law is also broken.

**Comment by turion** [comment]
I applied your fix, but it seems that still `select != selectM`. I'm a bit puzzled.

**Comment by turion** [comment]
Ah. I just had the order of `mappend` the wrong way around. Luckily I had used a noncommutative monoid.

**Comment by turion** [comment]
Ok, should be done now.

**Comment by snowleopard** [comment]
@turion Apologies for disappearing -- busy days! Will be back in action around Tuesday.

**Review by snowleopard — APPROVED** [review]
Looks good, thank you! I might do some light tweaks after merging. Apologies again for the delay in reviewing.

**Comment by snowleopard** [comment]
(Had to fix CI by changing `<>` to `mappend`.)

**Pull request merged**
